remote_branch: master

site_name: SpotX Mobile
site_url: https://spotxmobile.github.io
site_favicon: images/favicon.ico
copyright: 'Copyright (c) 2016 SpotXchange, Inc.'

pages:
  - Home: 'index.md'
  - Android:
    - SDK Quick Start: 'android/sdk.md'
    - Advanced Documentation: 'android/sdk-advanced.md'
    - Release Notes: 'android/release-notes.md'
  - iOS:
    - SDK Quick Start: 'ios/sdk.md'
    - Advanced Documentation: 'ios/sdk-advanced.md'
    - Release Notes: 'ios/release-notes.md'
  - Apple tvOS:
    - AVPlayer: 'tvos/avplayer-sdk.md'
    - TVML: 'tvos/tvml-sdk.md'
  - Adapters:
    - MoPub Android: 'adapters/mopub/android-adapter.md'
    - MoPub iOS: 'adapters/mopub/ios-adapter.md'
    - Brightcove Android: 'adapters/brightcove/android-adapter.md'
  - Other Integrations:
    - MoPub MRAID Creative: 'other-integrations/mopub-mraid-creative.md'
    - MoPub Rich Media Tag: 'other-integrations/mopub-rich-media.md'
  - IAB Categories: 'iab-categories.md'
  - Immutable Ad Parameters: immutable-ad-params.md

theme: material

extra_css:
  - 'css/spotx.css'

extra:
  logo: 'images/logo.png'
  palette:
    primary: 'green'
    accent: 'cyan'
  font:
      text: 'Open Sans'
      code: 'Roboto Mono'
  author:
    github: 'spotxmobile'

markdown_extensions:
  - admonition
  - codehilite(css_class=code)
  - smarty
  - toc:
      permalink: '#'
