remote_branch: master

site_name: SPOTX Mobile SDKs
site_url: https://spotxmobile.github.io
site_favicon: images/favicon.ico
copyright: 'Copyright (c) 2016 SpotXchange, Inc.'

pages:
  - Home: 'index.md'
  - Android: 'sdk-android.md'
  - iOS: 'spotx-sdk-ios.md'
  - Apple tvOS:
    - AVPlayer: 'spotx-sdk-avplayer.md'
    - TVML: 'spotx-sdk-tvml.md'
  - Adapters:
    - MoPub Android: 'spotx-mopub-android.md'
    - MoPub iOS: 'spotx-mopub-ios.md'


theme: material

extra_css:
  - 'css/spotx.css'

extra:
  logo: 'images/logo.png'
  palette:
    primary: 'green'
    accent: 'cyan'
  font:
      text: 'Open Sans'
      code: 'Roboto Mono'

markdown_extensions:
  - admonition
  - codehilite(css_class=code)
  - smarty
  - toc:
      permalink: '#'
